# Generated by Django 5.2.11 on 2026-03-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='services.subject'),
        ),
    ]
